[2022-04-11 19:18:33,585] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data.download_data_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 19:18:33,599] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data.download_data_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 19:18:33,599] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 19:18:33,600] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-11 19:18:33,600] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 19:18:33,619] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): download_data_task> on 2019-01-01 00:00:00+00:00
[2022-04-11 19:18:33,628] {standard_task_runner.py:52} INFO - Started process 353121 to run task
[2022-04-11 19:18:33,635] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data', 'download_data_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '1717', '--raw', '--subdir', 'DAGS_FOLDER/nfl_to_gcs.py', '--cfg-path', '/tmp/tmpk2zbpjha', '--error-file', '/tmp/tmp6z5puhmg']
[2022-04-11 19:18:33,636] {standard_task_runner.py:77} INFO - Job 1717: Subtask download_data_task
[2022-04-11 19:18:33,720] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data.download_data_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 4ed3eda454fd
[2022-04-11 19:18:33,792] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data
AIRFLOW_CTX_TASK_ID=download_data_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2022-04-11 19:18:33,799] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-11 19:18:33,800] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-04-11 19:18:33,801] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-04-11 19:18:33,802] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-04-11 19:18:33,802] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:18:33,803] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:18:33,804] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:18:33,805] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-04-11 19:18:33,806] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:18:33,806] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:18:33,807] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:18:33,808] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 19:18:39,513] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 37, in download_pbp_data
    pq.write_table(pbp_data,dest_file_template)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1986, in write_table
    **kwargs) as writer:
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 638, in __init__
    where, filesystem, allow_legacy_filesystem=True
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/fs.py", line 174, in _resolve_filesystem_and_path
    filesystem, path = FileSystem.from_uri(path)
  File "pyarrow/_fs.pyx", line 347, in pyarrow._fs.FileSystem.from_uri
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Cannot parse URI: 'raw/pbp_data/{{ execution_date.strftime('%Y') }}/pbp_data{{ execution_date.strftime('%Y-%m') }}.parquet'
[2022-04-11 19:18:39,529] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data, task_id=download_data_task, execution_date=20190101T000000, start_date=20220411T191833, end_date=20220411T191839
[2022-04-11 19:18:39,542] {standard_task_runner.py:92} ERROR - Failed to execute job 1717 for task download_data_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/nfl_to_gcs.py", line 37, in download_pbp_data
    pq.write_table(pbp_data,dest_file_template)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 1986, in write_table
    **kwargs) as writer:
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet.py", line 638, in __init__
    where, filesystem, allow_legacy_filesystem=True
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/fs.py", line 174, in _resolve_filesystem_and_path
    filesystem, path = FileSystem.from_uri(path)
  File "pyarrow/_fs.pyx", line 347, in pyarrow._fs.FileSystem.from_uri
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Cannot parse URI: 'raw/pbp_data/{{ execution_date.strftime('%Y') }}/pbp_data{{ execution_date.strftime('%Y-%m') }}.parquet'
[2022-04-11 19:18:39,564] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-11 19:18:39,604] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-11 20:07:26,849] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data.download_data_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 20:07:26,864] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data.download_data_task scheduled__2019-01-01T00:00:00+00:00 [queued]>
[2022-04-11 20:07:26,864] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 20:07:26,865] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-11 20:07:26,865] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-11 20:07:26,883] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): download_data_task> on 2019-01-01 00:00:00+00:00
[2022-04-11 20:07:26,893] {standard_task_runner.py:52} INFO - Started process 359275 to run task
[2022-04-11 20:07:26,899] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data', 'download_data_task', 'scheduled__2019-01-01T00:00:00+00:00', '--job-id', '2017', '--raw', '--subdir', 'DAGS_FOLDER/nfl_to_gcs.py', '--cfg-path', '/tmp/tmpvdzbax1f', '--error-file', '/tmp/tmpieb1zoxd']
[2022-04-11 20:07:26,901] {standard_task_runner.py:77} INFO - Job 2017: Subtask download_data_task
[2022-04-11 20:07:26,982] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data.download_data_task scheduled__2019-01-01T00:00:00+00:00 [running]> on host 4ed3eda454fd
[2022-04-11 20:07:27,058] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data
AIRFLOW_CTX_TASK_ID=download_data_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-01T00:00:00+00:00
[2022-04-11 20:07:27,065] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-11 20:07:27,066] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
[2022-04-11 20:07:27,067] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2022-04-11 20:07:27,068] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2022-04-11 20:07:27,069] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:07:27,070] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:07:27,071] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:07:27,072] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
[2022-04-11 20:07:27,073] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:07:27,074] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:07:27,075] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:07:27,076] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
[2022-04-11 20:07:36,579] {python.py:175} INFO - Done. Returned value was: None
[2022-04-11 20:07:36,595] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data, task_id=download_data_task, execution_date=20190101T000000, start_date=20220411T200726, end_date=20220411T200736
[2022-04-11 20:07:36,640] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-11 20:07:36,714] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
