[2022-04-24 14:46:18,821] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:46:18,836] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [queued]>
[2022-04-24 14:46:18,837] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:46:18,837] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-24 14:46:18,837] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-24 14:46:18,856] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2007-01-01 00:00:00+00:00
[2022-04-24 14:46:18,869] {standard_task_runner.py:52} INFO - Started process 2898 to run task
[2022-04-24 14:46:18,886] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2007-01-01T00:00:00+00:00', '--job-id', '2181', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp1m0og770', '--error-file', '/tmp/tmpe2vy9weo']
[2022-04-24 14:46:18,888] {standard_task_runner.py:77} INFO - Job 2181: Subtask bq_ext_2_part_task
[2022-04-24 14:46:19,046] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [running]> on host 28475d5c3e7a
[2022-04-24 14:46:19,207] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2007-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2007-01-01T00:00:00+00:00
[2022-04-24 14:46:19,209] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-24 14:46:19,224] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-24 14:46:19,247] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2007_01_01T00_00_00_00_00_145620d6228d22c791772689aed125b9
[2022-04-24 14:46:23,284] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20070101T000000, start_date=20220424T144618, end_date=20220424T144623
[2022-04-24 14:46:23,336] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-24 14:46:23,373] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:36:00,814] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:36:00,842] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:36:00,852] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:36:00,852] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:36:00,853] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:36:00,871] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2007-01-01 00:00:00+00:00
[2022-04-25 12:36:00,891] {standard_task_runner.py:52} INFO - Started process 650 to run task
[2022-04-25 12:36:00,902] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2007-01-01T00:00:00+00:00', '--job-id', '2338', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp6t3fwb_l', '--error-file', '/tmp/tmp_k4ico69']
[2022-04-25 12:36:00,903] {standard_task_runner.py:77} INFO - Job 2338: Subtask bq_ext_2_part_task
[2022-04-25 12:36:01,043] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:36:01,156] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2007-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2007-01-01T00:00:00+00:00
[2022-04-25 12:36:01,158] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:36:01,168] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:36:01,179] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2007_01_01T00_00_00_00_00_b27c894e1288ce13f9289e336483a3bc
[2022-04-25 12:36:05,498] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20070101T000000, start_date=20220425T123600, end_date=20220425T123605
[2022-04-25 12:36:05,555] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 12:36:05,597] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:42:56,009] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:42:56,024] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:42:56,024] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:42:56,025] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:42:56,025] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:42:56,043] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2007-01-01 00:00:00+00:00
[2022-04-25 12:42:56,049] {standard_task_runner.py:52} INFO - Started process 1622 to run task
[2022-04-25 12:42:56,060] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2007-01-01T00:00:00+00:00', '--job-id', '2385', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp_c1u65x_', '--error-file', '/tmp/tmp69a4cbh5']
[2022-04-25 12:42:56,062] {standard_task_runner.py:77} INFO - Job 2385: Subtask bq_ext_2_part_task
[2022-04-25 12:42:56,158] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:42:56,257] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2007-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2007-01-01T00:00:00+00:00
[2022-04-25 12:42:56,261] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:42:56,273] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:42:56,287] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2007_01_01T00_00_00_00_00_8ce0186a17c1002c2fad9ef8e1a9a7c8
[2022-04-25 12:43:00,584] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20070101T000000, start_date=20220425T124256, end_date=20220425T124300
[2022-04-25 12:43:00,609] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-25 12:43:00,639] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-25 12:44:10,473] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:44:10,487] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [queued]>
[2022-04-25 12:44:10,488] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:44:10,488] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-25 12:44:10,488] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 12:44:10,503] {taskinstance.py:1259} INFO - Executing <Task(BigQueryInsertJobOperator): bq_ext_2_part_task> on 2007-01-01 00:00:00+00:00
[2022-04-25 12:44:10,512] {standard_task_runner.py:52} INFO - Started process 1858 to run task
[2022-04-25 12:44:10,523] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'pbp_data_bq_dag', 'bq_ext_2_part_task', 'scheduled__2007-01-01T00:00:00+00:00', '--job-id', '2404', '--raw', '--subdir', 'DAGS_FOLDER/nfl_gcs_to_bq.py', '--cfg-path', '/tmp/tmp6hjty6m9', '--error-file', '/tmp/tmprm4vs_1f']
[2022-04-25 12:44:10,524] {standard_task_runner.py:77} INFO - Job 2404: Subtask bq_ext_2_part_task
[2022-04-25 12:44:10,627] {logging_mixin.py:109} INFO - Running <TaskInstance: pbp_data_bq_dag.bq_ext_2_part_task scheduled__2007-01-01T00:00:00+00:00 [running]> on host de169a1be7ed
[2022-04-25 12:44:10,718] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pbp_data_bq_dag
AIRFLOW_CTX_TASK_ID=bq_ext_2_part_task
AIRFLOW_CTX_EXECUTION_DATE=2007-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2007-01-01T00:00:00+00:00
[2022-04-25 12:44:10,720] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-04-25 12:44:10,734] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 12:44:10,747] {bigquery.py:1637} INFO - Inserting job ***_pbp_data_bq_dag_bq_ext_2_part_task_2007_01_01T00_00_00_00_00_0a294a865a50c78943043178b98af438
[2022-04-25 12:44:11,560] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_4_player_id' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2007_01_01T00_00_00_00_00_0a294a865a50c78943043178b98af438)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:44:11,593] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=pbp_data_bq_dag, task_id=bq_ext_2_part_task, execution_date=20070101T000000, start_date=20220425T124410, end_date=20220425T124411
[2022-04-25 12:44:11,624] {standard_task_runner.py:92} ERROR - Failed to execute job 2404 for task bq_ext_2_part_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2287, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2253, in _submit_job
    job_id=job_id,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 430, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1639, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1447, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1437, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading table: nfl_project.external_pbp_data, error message: Parquet column 'assist_tackle_4_player_id' has type DOUBLE which does not match the target cpp_type STRING_PIECE.

(job ID: airflow_pbp_data_bq_dag_bq_ext_2_part_task_2007_01_01T00_00_00_00_00_0a294a865a50c78943043178b98af438)

                                                                                                                -----Query Job SQL Follows-----                                                                                                                

    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
   1:CREATE OR REPLACE TABLE nfl_project.pbp_data_partitioned                     PARTITION BY DATE(game_timestamp) AS                     SELECT *, PARSE_TIMESTAMP('%F', game_date) AS game_timestamp                     FROM nfl_project.external_pbp_data;
    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
[2022-04-25 12:44:11,665] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 12:44:11,720] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
